### PR TITLE
adding test circle config and badge to readme

### LINKED ISSUE #2: CircleCI Integration
Following up here on suggestion from @vsoch in #1 suggesting a CircleCI integration. Love the idea! I did a little research into CircleCI, and came up with some ideas for what we might want to do:
1. confirm that we can build a Singularity container without an error from our `Singularity` build file,
2. confirm that we can compile our LaTeX without errors via the Singularity container (e.g., via `singularity run`),
3. :question: confirm that Singularity-compiled pdf matches a canonical version (e.g., in `example`),
4. confirm that we can build a Docker container without an error from our `Docker` build file,
5. confirm that we can compile our LaTeX without errors via the Docker container (e.g., via `Docker run`),
6. :question: confirm that Docker-compiled pdf matches a canonical version (e.g., in `example`),
7. :question: :question: deploy the Docker container via DockerHub when merged into master.
   * I know that SingularityHub builds containers for you, but I'm not as familiar with Dockerhub. I saw this kind of continuous-deployment mentioned in an intro on CircleCI.

Would love some feedback if I'm on the right track about the kinds of good things that are possible with CircleCI! :racing_car: :racing_car:

### PR DESCRIPTION
**Pull request by vsoch**
This is the first attempt to add the CircleCI configuration to build the container during testing, test by generating a PDF (and saving the result as an artifact) and on merge to master pushing to Docker Hub. This build does not do anything with Singularity, as the user could use the docker build via singularity, e.g.,

```
singularity pull docker://mmore500/presentation-template
```

This will close #2 Note to @mmore500 getting circle working always takes a few tries, I'll keep updating the PR until it's green :)

### CODE REVIEW

**Comment by vsoch** [comment]
Note that I just changed the setting to build pull requests:

image

And I'll need to do a trivial push to trigger it. I also canceled redundant builds, which is something you want to do to not waste minutes on Circle!

**Comment by vsoch** [comment]
@mmore500 so you see where it's building --> https://circleci.com/gh/mmore500/presentation-template/3#usage-queue/containers/0 This is a heavy container so it will take a bit of time. The "in progress" color is blue, red is fail, green is pass. This particular job is just the build, after there is one called "save_cache" that caches some of the layers for next time, and if you look at the "jobs" and then corresponding sections of the CircleCI file that's where all the commands are. The workflow at the bottom determines when things run based on the branch. So you'll notice that the final deploy job only runs on commit to master, and this includes a merge from a PR.

**Comment by vsoch** [comment]
Holy crap, it built the first time! This seriously never happens :) 

Check out the artifacts here --> https://circleci.com/gh/mmore500/presentation-template/3#artifacts/containers/0g

**Comment by vsoch** [comment]
Here is the PDF --> https://3-110734911-gh.circle-artifacts.com/0/pdf-files/mypdf.pdf

I'm going to merge, which should trigger master to do the build --> deploy. If you've set up the DOCKER environment variables correctly, this should deploy a new "latest" tag along with the commit that is merged. If it doesn't work I'll take a look and help to debug what might be up.

**Comment by mmore500** [comment]
This is beautiful!

**Comment by vsoch** [comment]
Should actually deploy with the fix I just did - I removed your environment variable from Circle and added it to the builder config instead.

**Comment by mmore500** [comment]
I'll plan to check on it in an hour or so :clock1:

**Comment by vsoch** [comment]
hey @mmore500 congrats, the build finished and deployed:

https://circleci.com/workflow-run/1e26f8f6-17c5-46fa-b89d-8cc87ca7c1d1

and you are all green!

image

See the new tags here:

https://hub.docker.com/r/mmore500/presentation-template/tags/

And the artifacts are stored in the "artifacts" tab of the build job step:

https://circleci.com/gh/mmore500/presentation-template/8#artifacts/containers/0

There is a lot of fun you can do with CI, basically any kind of github pages thing, pushing / deploying artifacts / containers, or other! Enjoy your new tools and knowledge and please ping me if you ever want help or to collaborate on something fun. Happy Hacktoberfest! :jack_o_lantern:

**Comment by mmore500** [comment]
Thank you for your contributions and for helping me learn some new things along the way!  :books: It's always fun working with a new collaborator.

Bumped the version up to 1.1.0 to reflect the addition of Docker support. :tada:

**Pull request merged**
